# Site settings
title: Практикум на ЭВМ, семестр 5
email: andrey.zenderro@math.msu.ru
description: "

"
baseurl: "/programming-semester-5/" # the subpath of your site, e.g. /blog/
url: "https://zenderro.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  zenderro

# Build settings
markdown: kramdown
